/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_PaqueteRPC (XDR *xdrs, PaqueteRPC *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_arg (XDR *xdrs, set_value_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->key, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_value2, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_ret (XDR *xdrs, get_value_ret *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_value2, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key_arg (XDR *xdrs, key_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->key, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
