/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_destroy_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_destroy, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_set_value_1(struct set_value_arg arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_set_value,
		(xdrproc_t) xdr_set_value_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_get_value_1(struct key_arg arg1, struct get_value_ret *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_get_value,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_get_value_ret, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_modify_value_1(struct set_value_arg arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_modify_value,
		(xdrproc_t) xdr_set_value_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_delete_key_1(struct key_arg arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_delete_key,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_exist_1(struct key_arg arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_exist,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
