/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct PaqueteRPC {
	int x;
	int y;
	int z;
};
typedef struct PaqueteRPC PaqueteRPC;

struct set_value_arg {
	char key[256];
	char value1[256];
	int N_value2;
	float V_value2[32];
	struct PaqueteRPC value3;
};
typedef struct set_value_arg set_value_arg;

struct get_value_ret {
	int status;
	char value1[256];
	int N_value2;
	float V_value2[32];
	struct PaqueteRPC value3;
};
typedef struct get_value_ret get_value_ret;

struct key_arg {
	char key[256];
};
typedef struct key_arg key_arg;

#define CLAVES 100522255
#define CLAVES_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1(int *, CLIENT *);
extern  bool_t rpc_destroy_1_svc(int *, struct svc_req *);
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1(struct set_value_arg , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(struct set_value_arg , int *, struct svc_req *);
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1(struct key_arg , struct get_value_ret *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(struct key_arg , struct get_value_ret *, struct svc_req *);
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1(struct set_value_arg , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(struct set_value_arg , int *, struct svc_req *);
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1(struct key_arg , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(struct key_arg , int *, struct svc_req *);
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1(struct key_arg , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(struct key_arg , int *, struct svc_req *);
extern int claves_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1();
extern  bool_t rpc_destroy_1_svc();
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int claves_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PaqueteRPC (XDR *, PaqueteRPC*);
extern  bool_t xdr_set_value_arg (XDR *, set_value_arg*);
extern  bool_t xdr_get_value_ret (XDR *, get_value_ret*);
extern  bool_t xdr_key_arg (XDR *, key_arg*);

#else /* K&R C */
extern bool_t xdr_PaqueteRPC ();
extern bool_t xdr_set_value_arg ();
extern bool_t xdr_get_value_ret ();
extern bool_t xdr_key_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
