/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clavesRPC.h"
#include "claves.h"

bool_t
rpc_destroy_1_svc(int *result, struct svc_req *rqstp)
{
	*result = destroy();

	return TRUE;
}

bool_t
rpc_set_value_1_svc(struct set_value_arg arg1, int *result,  struct svc_req *rqstp)
{
	// Creamos la estructura Paquete
	struct Paquete value3;
	value3.x = arg1.value3.x;
	value3.y = arg1.value3.y;
	value3.z = arg1.value3.z;
	
	*result = set_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2, value3);

	return TRUE;
}

bool_t
rpc_get_value_1_svc(struct key_arg arg1, struct get_value_ret *result,  struct svc_req *rqstp)
{
	struct Paquete value3;
	
	result->status = get_value(arg1.key, result->value1, &result->N_value2, result->V_value2, &value3);

	// Si la clave existe --> pasamos los datos al struct Paquete
	if (result->status == 0) {
		result->value3.x = value3.x;
		result->value3.y = value3.y;
		result->value3.z = value3.z;
	}

	return TRUE;
}

bool_t
rpc_modify_value_1_svc(struct set_value_arg arg1, int *result,  struct svc_req *rqstp)
{
	// Creamos la estructura Paquete
	struct Paquete value3;
	value3.x = arg1.value3.x;
	value3.y = arg1.value3.y;
	value3.z = arg1.value3.z;
	
	*result = modify_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2, value3);

	return TRUE;
}

bool_t
rpc_delete_key_1_svc(struct key_arg arg1, int *result,  struct svc_req *rqstp)
{
	*result = delete_key(arg1.key);

	return TRUE;
}

bool_t
rpc_exist_1_svc(struct key_arg arg1, int *result,  struct svc_req *rqstp)
{
	*result = exist(arg1.key);

	return TRUE;
}

int
claves_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
