/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registro.h"

bool_t
imprimir_log_1_svc(struct operacion_usuario argumentos, int *result,  struct svc_req *rqstp)
{

	bool_t retval = TRUE;
    
    if (strlen(argumentos.nombrefichero) != 0 && strcmp(argumentos.nombrefichero, "") != 0)
    {
        // Tiene fichero adjunto (SENDATTACH)
        printf("%s %s %s\n", argumentos.nombre, argumentos.operacion, argumentos.nombrefichero);
    }
    else
    {
        // Sin fichero adjunto (REGISTER, CONNECT, SEND, etc.)
        printf("%s %s\n", argumentos.nombre, argumentos.operacion);
    }
    
    fflush(stdout);
    return retval;
}

int
logsrpc_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
