/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "registro.h"

bool_t
xdr_operacion_usuario (XDR *xdrs, operacion_usuario *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombre, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombrefichero, 256))
		 return FALSE;
	return TRUE;
}
