/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTRO_H_RPCGEN
#define _REGISTRO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct operacion_usuario {
	char *nombre;
	char *operacion;
	char *nombrefichero;
};
typedef struct operacion_usuario operacion_usuario;

#define LOGSRPC_PROG 100522255
#define LOGSRPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR_LOG 1
extern  enum clnt_stat imprimir_log_1(struct operacion_usuario , int *, CLIENT *);
extern  bool_t imprimir_log_1_svc(struct operacion_usuario , int *, struct svc_req *);
extern int logsrpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR_LOG 1
extern  enum clnt_stat imprimir_log_1();
extern  bool_t imprimir_log_1_svc();
extern int logsrpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operacion_usuario (XDR *, operacion_usuario*);

#else /* K&R C */
extern bool_t xdr_operacion_usuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTRO_H_RPCGEN */
