/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "registro.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
imprimir_log_1(struct operacion_usuario argumentos, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, IMPRIMIR_LOG,
		(xdrproc_t) xdr_operacion_usuario, (caddr_t) &argumentos,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
